<a href="https://colab.research.google.com/github/Sreejithjayachandran/Assessment-2-Numpy-Pandas/blob/main/Assessment_2__Numpy_%26_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Q1
# Shape of the array
# Data type of the array


# Create the NumPy array
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

# Display the array, its shape, and data type
print("The array:", arr)
print("Shape of the array:", arr.shape)
print("Data type of the array:", arr.dtype)

The array: [10 20 30 40 50]
Shape of the array: (5,)
Data type of the array: int64

In [ ]:
#Q2
# Add 5 to every element.
# Multiply every element by 2.

# Create the NumPy array
import numpy as np
arr=np.array([5,10,15,20,25])

#Add 5 to every element
arr_new1=arr*5
print(f"Add 5 : {arr_new1}")


#Multiply with 2
arr_new2=arr*2
print(f"multiply with 2 : {arr}")

Add 5 : [ 25  50  75 100 125]
multiply with 2 : [ 5 10 15 20 25]

In [ ]:
#Q3

import numpy as np
def describe_array_stats(data):
    # Perform calculations
    arr_mean = np.mean(data)
    arr_median = np.median(data)
    arr_min = np.min(data)
    arr_max = np.max(data)
    arr_std = np.std(data)

    # Print results with descriptions
    print("NumPy Statistical operations")
    print(f"Mean: {arr_mean}")
    print(f"Median: {arr_median}")
    print(f"Minimum: {arr_min}")
    print(f"Maximum: {arr_max}")
    print(f"Standard Deviation: {arr_std:.4f}")

# Given array
arr = np.array([12, 15, 18, 20, 25, 30])

# Call the function
describe_array_stats(arr)

NumPy Statistical operations
Mean: 20.0
Median: 19.0
Minimum: 12
Maximum: 30
Standard Deviation: 6.0277

In [ ]:
#Q4
#Using NumPy, extract all values that are greater than 40

import numpy as np

# Given
arr = np.array([10, 25, 30, 45, 50, 65, 70])

# Extract values greater than 40
filtered_arr = arr[arr > 40]

# Display result
print("Filtered array with values greater than 40:", filtered_arr)

Filtered array with values greater than 40: [45 50 65 70]

In [ ]:
#Q5
#Create the following DataFrame using Pandas


# Create the DataFrame using pandas
import pandas as pd
df=pd.DataFrame({
    'Name':['Anu','Rahul','Meera','Arun'],
    'Age':[21,22,20,23],
    'Score':[85,72,91,68]
})
# Display DataFrame.
df

    Name  Age  Score
0    Anu   21     85
1  Rahul   22     72
2  Meera   20     91
3   Arun   23     68

In [ ]:
import pandas as pd

# Q6
# Display only the Name and Score columns.
# Display the complete record of Meera

# Display only the Name and Score columns
print("Name and Score columns:")
display(df[['Name', 'Score']])

# Display the complete record of Meera
print("\nComplete record of Meera:")
display(df[df['Name'] == 'Meera'])

Name and Score columns:

    Name  Score
0    Anu     85
1  Rahul     72
2  Meera     91
3   Arun     68

Complete record of Meera:

    Name  Age  Score
2  Meera   20     91

In [ ]:
#Q7
# Using the DataFrame from Q5, display all students whose Score is greater than 75

# Filter students with Score > 75
filtered_df = df[df['Score'] > 75]

# Display the results
display(filtered_df)

    Name  Age  Score
0    Anu   21     85
2  Meera   20     91

In [ ]:
#Q8
# Using the DataFrame from Q5, display:
# 1. Number of rows and columns
# 2. Column names
# 3. Data types
# 4. Basic statistical summary

# 1. Number of rows and columns
print("1. Shape (Rows, Columns):")
print(df.shape)

# 2. Column names
print("\n2. Column Names:")
print(df.columns.tolist())

# 3. Data types
print("\n3. Data Types:")
print(df.dtypes)

# 4. Basic statistical summary
print("\n4. Basic Statistical Summary:")
display(df.describe())

1. Shape (Rows, Columns):
(4, 3)

2. Column Names:
['Name', 'Age', 'Score']

3. Data Types:
Name     object
Age       int64
Score     int64
dtype: object

4. Basic Statistical Summary:

             Age      Score
count   4.000000   4.000000
mean   21.500000  79.000000
std     1.290994  10.801234
min    20.000000  68.000000
25%    20.750000  71.000000
50%    21.500000  78.500000
75%    22.250000  86.500000
max    23.000000  91.000000

In [ ]:
#Q9
# Sort the DataFrame from Q5 by Score in descending order.

#sort
sorted_df = df.sort_values(by='Score', ascending=False)

#display
display(sorted_df)

    Name  Age  Score
2  Meera   20     91
0    Anu   21     85
1  Rahul   22     72
3   Arun   23     68

In [ ]:
#Q10
# 1. Identify missing values
# 2. Replace missing Age with mean age
# 3. Replace missing Score with mean score

import numpy as np
import pandas as pd

# given DataFrame
df_missing = pd.DataFrame({
    'Name': ['A', 'B', 'C', 'D'],
    'Age': [21, np.nan, 23, 22],
    'Score': [80, 75, np.nan, 90]
})

# 1. Identify the missing values
print("\n1. Missing values map:")
display(df_missing.isnull())

# Calculate means
mean_age = df_missing['Age'].mean()
mean_score = df_missing['Score'].mean()

# 2 & 3. Replace missing values with means
df_missing['Age'] = df_missing['Age'].fillna(mean_age)
df_missing['Score'] = df_missing['Score'].fillna(mean_score)

#display
print("\n2.DataFrame after replacing values:")
display(df_missing)

1. Missing values map:

    Name    Age  Score
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False

2.DataFrame after replacing values:

  Name   Age      Score
0    A  21.0  80.000000
1    B  22.0  75.000000
2    C  23.0  81.666667
3    D  22.0  90.000000

In [37]:
#Q11 Load student_performance into a Pandas DataFrame



import pandas as pd

# 1.1. Read the student_performance dataset
file_path = "/content/drive/MyDrive/DSA/Assessment/Assessment 2  Numpy & Pandas/student_performance.csv"
df_student_perf = pd.read_csv(file_path)
display(df_student_perf.head())
print("\n")

# 1. Display the first 5 records
print("Q_11.1 First 5 records:")
display(df.head())

# 2. Display the last 5 records
print("\n Q_11.2  Last 5 records:")
display(df.tail())

# 3. Find the number of rows and columns
print(f"\n Q_11.3  Number of rows: {df.shape[0]}, Number of columns: {df.shape[1]}")

# 4. Display the column names
print("\nQ_11.4  Column names:")
print(df.columns.tolist())

# 5. Display the data types
print("\nQ-11.5  Data types:")
print(df.dtypes)

# 6. Generate a statistical summary of the numerical columns
print("\nQ_11.6 Statistical summary of numerical columns:")
display(df.describe())

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7
1,STU1002,Kiran Pillai,Male,Computer Science,24.0,75.5,70.3,63.1,65.1,62.3,60.3
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1
3,STU1004,Rahul Sharma,Female,Data Science,25.0,80.4,65.8,50.7,52.6,48.8,57.2
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9

Q_11.1 First 5 records:

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7
1,STU1002,Kiran Pillai,Male,Computer Science,24.0,75.5,70.3,63.1,65.1,62.3,60.3
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1
3,STU1004,Rahul Sharma,Female,Data Science,25.0,80.4,65.8,50.7,52.6,48.8,57.2
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9

 Q_11.2  Last 5 records:

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
75,STU1076,Priya Kumar,Female,Computer Science,24.0,99.3,46.9,57.6,29.5,57.1,47.2
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2
78,STU1079,Meera Thomas,Male,Electronics,23.0,99.4,64.6,66.5,61.8,52.5,63.4
79,STU1080,Diya Varma,Male,Electronics,19.0,86.4,80.5,94.3,58.6,74.9,78.6

 Q_11.3  Number of rows: 80, Number of columns: 11

Q_11.4  Column names:
['Student_ID', 'Name', 'Gender', 'Department', 'Age', 'Attendance', 'Python_Score', 'SQL_Score', 'Pandas_Score', 'NumPy_Score', 'Final_Score']

Q-11.5  Data types:
Student_ID       object
Name             object
Gender           object
Department       object
Age             float64
Attendance      float64
Python_Score    float64
SQL_Score       float64
Pandas_Score    float64
NumPy_Score     float64
Final_Score     float64
dtype: object

Q_11.6 Statistical summary of numerical columns:

,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
count,77.000000,77.000000,78.000000,80.000000,78.000000,78.000000,78.000000
mean,22.012987,81.672727,72.821795,70.445000,70.365385,68.574359,70.696154
std,2.155126,10.054204,16.722103,14.630417,15.814294,16.417242,14.053871
min,19.000000,56.300000,39.500000,38.300000,25.000000,25.000000,40.600000
25%,20.000000,75.500000,64.525000,60.650000,61.800000,57.175000,60.450000
50%,22.000000,81.100000,72.000000,69.300000,70.000000,70.700000,70.950000
75%,24.000000,86.400000,86.525000,81.150000,82.575000,80.650000,82.275000
max,25.000000,100.000000,100.000000,100.000000,100.000000,100.000000,97.000000

In [39]:
# Q12: Filtering and Sorting


# 1. Find students whose Final_Score is greater than 75
print(" Q12.1. Students with Final_Score > 75:")
df_high_score = df[df['Final_Score'] > 75]
display(df_high_score)

# 2. Find students whose Attendance is below 75%
print("\nQ12.2. Students with Attendance < 75%:")
df_low_attendance = df[df['Attendance'] < 75]
display(df_low_attendance)

# 3. Find students from the Data Science department with Final_Score greater than 80
print("\nQ12.3. Data Science students with Final_Score > 80:")
df_ds_high_score = df[(df['Department'] == 'Data Science') & (df['Final_Score'] > 80)]
display(df_ds_high_score)

# 4. Sort all students by Final_Score from highest to lowest
print("\nQ12.4. All students sorted by Final_Score (highest to lowest):")
df_sorted = df.sort_values(by='Final_Score', ascending=False)
display(df_sorted)

 Q12.1. Students with Final_Score > 75:

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9
6,STU1007,Akhil Varma,Male,Electronics,22.0,73.2,81.7,82.2,81.5,64.2,77.0
7,STU1008,Akhil Varma,Male,Computer Science,20.0,81.1,72.1,80.4,72.9,73.5,79.2
8,STU1009,Diya Menon,Male,Data Science,25.0,64.4,94.8,86.0,87.7,100.0,83.0
10,STU1011,Diya Das,Female,Data Science,20.0,100.0,100.0,93.2,100.0,89.3,91.9
11,STU1012,Arun Reddy,Male,Electronics,20.0,69.1,80.4,78.0,88.9,77.1,86.9
16,STU1017,Rahul Thomas,Female,Data Science,25.0,78.3,80.8,99.4,77.2,100.0,91.1
17,STU1018,Priya Nair,Male,Data Science,19.0,85.4,62.6,81.6,79.6,75.5,75.1
23,STU1024,Fathima Joseph,Female,Commerce,23.0,78.2,87.7,71.0,88.5,74.8,83.7
24,STU1025,Kiran Varma,Female,Electronics,21.0,80.7,87.5,67.1,84.5,96.1,77.3
27,STU1028,Nikhil Nair,Female,Data Science,24.0,79.3,70.3,82.0,64.4,72.8,77.1
30,STU1031,Amal Varma,Female,Computer Science,19.0,86.7,86.9,64.3,100.0,89.2,85.5
33,STU1034,Amal Das,Male,Computer Science,19.0,85.5,94.4,81.6,71.3,81.5,84.3
35,STU1036,Maya Menon,Female,Electronics,19.0,82.0,95.3,93.4,100.0,62.5,84.2
37,STU1038,Kiran Pillai,Female,Electronics,25.0,85.2,87.8,78.3,85.5,82.7,82.4
39,STU1040,Rohan Sharma,Female,Computer Science,21.0,100.0,68.9,79.8,66.1,66.4,78.5
40,STU1041,Amal Pillai,Female,Computer Science,25.0,97.7,94.3,91.0,73.1,91.2,94.5
41,STU1042,Arun Joseph,Female,Computer Science,21.0,85.9,71.2,76.1,70.8,NaN,77.9
43,STU1044,Rahul Das,Female,Computer Science,22.0,70.9,68.0,67.3,83.6,76.7,77.3
47,STU1048,Priya Kumar,Male,Data Science,25.0,64.6,80.6,67.0,71.2,80.2,77.3
48,STU1049,Asha Sharma,Male,Data Science,22.0,91.3,88.9,95.0,NaN,94.5,97.0
51,STU1052,Gokul Nair,Female,Commerce,25.0,77.3,80.4,85.3,96.7,83.5,79.3
55,STU1056,Vivek Varma,Male,Data Science,22.0,81.0,87.0,95.1,88.4,75.7,93.3
56,STU1057,Rohan Pillai,Female,Commerce,20.0,79.5,72.1,66.9,61.8,72.3,75.2
57,STU1058,Diya Thomas,Female,Computer Science,23.0,83.5,93.1,78.8,91.6,83.8,92.3
58,STU1059,Anu Menon,Male,Electronics,24.0,96.7,99.7,77.1,68.9,89.7,84.9
59,STU1060,Asha Menon,Male,Data Science,19.0,56.3,100.0,85.0,87.4,57.4,87.9
61,STU1062,Kiran Pillai,Female,Computer Science,19.0,83.8,100.0,100.0,89.4,91.4,96.0
64,STU1065,Rohan Sharma,Male,Computer Science,19.0,64.4,96.5,69.3,86.7,80.7,83.5
67,STU1068,Maya Das,Female,Computer Science,23.0,66.7,83.4,79.6,89.3,83.6,83.7
73,STU1074,Anu Kumar,Female,Computer Science,22.0,95.0,95.3,67.7,92.4,81.4,83.4
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2
79,STU1080,Diya Varma,Male,Electronics,19.0,86.4,80.5,94.3,58.6,74.9,78.6

Q12.2. Students with Attendance < 75%:

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9
6,STU1007,Akhil Varma,Male,Electronics,22.0,73.2,81.7,82.2,81.5,64.2,77.0
8,STU1009,Diya Menon,Male,Data Science,25.0,64.4,94.8,86.0,87.7,100.0,83.0
9,STU1010,Gokul Pillai,Female,Computer Science,19.0,67.3,79.6,85.0,74.1,80.5,73.8
11,STU1012,Arun Reddy,Male,Electronics,20.0,69.1,80.4,78.0,88.9,77.1,86.9
15,STU1016,Nikhil Kumar,Female,Computer Science,NaN,70.3,55.9,69.3,67.1,58.4,58.2
19,STU1020,Vivek Sharma,Female,Commerce,22.0,72.1,65.8,60.9,49.8,44.8,54.6
25,STU1026,Maya Menon,Male,Electronics,20.0,68.3,91.7,64.5,83.5,73.7,69.4
36,STU1037,Nikhil Menon,Male,Electronics,22.0,74.8,69.5,60.7,64.6,81.6,69.1
42,STU1043,Sneha Varma,female,Data Science,19.0,74.4,71.8,79.1,69.8,95.9,NaN
43,STU1044,Rahul Das,Female,Computer Science,22.0,70.9,68.0,67.3,83.6,76.7,77.3
47,STU1048,Priya Kumar,Male,Data Science,25.0,64.6,80.6,67.0,71.2,80.2,77.3
50,STU1051,Gokul Menon,Male,Data Science,25.0,70.9,68.6,81.0,64.0,63.0,70.5
59,STU1060,Asha Menon,Male,Data Science,19.0,56.3,100.0,85.0,87.4,57.4,87.9
64,STU1065,Rohan Sharma,Male,Computer Science,19.0,64.4,96.5,69.3,86.7,80.7,83.5
67,STU1068,Maya Das,Female,Computer Science,23.0,66.7,83.4,79.6,89.3,83.6,83.7
71,STU1072,Vivek Pillai,Male,Commerce,24.0,71.5,59.0,58.2,56.3,48.9,56.6

Q12.3. Data Science students with Final_Score > 80:

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9
8,STU1009,Diya Menon,Male,Data Science,25.0,64.4,94.8,86.0,87.7,100.0,83.0
10,STU1011,Diya Das,Female,Data Science,20.0,100.0,100.0,93.2,100.0,89.3,91.9
16,STU1017,Rahul Thomas,Female,Data Science,25.0,78.3,80.8,99.4,77.2,100.0,91.1
48,STU1049,Asha Sharma,Male,Data Science,22.0,91.3,88.9,95.0,NaN,94.5,97.0
55,STU1056,Vivek Varma,Male,Data Science,22.0,81.0,87.0,95.1,88.4,75.7,93.3
59,STU1060,Asha Menon,Male,Data Science,19.0,56.3,100.0,85.0,87.4,57.4,87.9

Q12.4. All students sorted by Final_Score (highest to lowest):

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
48,STU1049,Asha Sharma,Male,Data Science,22.0,91.3,88.9,95.0,NaN,94.5,97.0
61,STU1062,Kiran Pillai,Female,Computer Science,19.0,83.8,100.0,100.0,89.4,91.4,96.0
40,STU1041,Amal Pillai,Female,Computer Science,25.0,97.7,94.3,91.0,73.1,91.2,94.5
55,STU1056,Vivek Varma,Male,Data Science,22.0,81.0,87.0,95.1,88.4,75.7,93.3
57,STU1058,Diya Thomas,Female,Computer Science,23.0,83.5,93.1,78.8,91.6,83.8,92.3
...,...,...,...,...,...,...,...,...,...,...,...
34,STU1035,Rahul Pillai,Female,Data Science,22.0,82.5,41.4,44.4,53.8,43.2,44.2
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5
26,STU1027,Aditya Pillai,Female,Computer Science,25.0,79.6,44.0,52.5,25.0,25.0,40.6
42,STU1043,Sneha Varma,female,Data Science,19.0,74.4,71.8,79.1,69.8,95.9,NaN
53,STU1054,Maya Sharma,Male,Data Science,19.0,82.5,59.7,60.5,65.8,73.3,NaN

In [43]:
# Q13: Feature Creation
import pandas as pd
import numpy as np

# Calculate Average_Technical_Score
technical_score = ['Python_Score', 'SQL_Score', 'Pandas_Score', 'NumPy_Score']
df['Average_Technical_Score'] = df[technical_score].mean(axis=1)

# Define categorization function
def assign_performance(score):
    if score >= 90:
        return 'Excellent'
    elif score >= 75:
        return 'Good'
    elif score >= 60:
        return 'Average'
    else:
        return 'Needs Improvement'

#  create the Performance column
df['Performance'] = df['Average_Technical_Score'].apply(assign_performance)

# Display the final DataFrame
display(df)

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score,Average_Technical_Score,Performance
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7,83.575,Good
1,STU1002,Kiran Pillai,Male,Computer Science,24.0,75.5,70.3,63.1,65.1,62.3,60.3,65.200,Average
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1,73.400,Average
3,STU1004,Rahul Sharma,Female,Data Science,25.0,80.4,65.8,50.7,52.6,48.8,57.2,54.475,Needs Improvement
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9,83.275,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,STU1076,Priya Kumar,Female,Computer Science,24.0,99.3,46.9,57.6,29.5,57.1,47.2,47.775,Needs Improvement
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5,46.525,Needs Improvement
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2,80.250,Good
78,STU1079,Meera Thomas,Male,Electronics,23.0,99.4,64.6,66.5,61.8,52.5,63.4,61.350,Average
79,STU1080,Diya Varma,Male,Electronics,19.0,86.4,80.5,94.3,58.6,74.9,78.6,77.075,Good

In [52]:
# Q14: GroupBy Analysis

# Group by student database
df_student_group = df.groupby('Department').agg(
    Number_of_Students=('Student_ID', 'count'),
    Average_Final_Score=('Final_Score', 'mean'),
    Maximum_Final_Score=('Final_Score', 'max'),
    Minimum_Final_Score=('Final_Score', 'min')
)

# Sort the resulting- Average Final Score in descending order
df_student_group_sorted = df_student_group.sort_values(by='Average_Final_Score', ascending=False)

# Display the resulting DataFrame
display(df_student_group_sorted)

,Number_of_Students,Average_Final_Score,Maximum_Final_Score,Minimum_Final_Score
Department,,,,
Electronics,13,72.846154,86.9,51.2
Computer Science,29,71.479310,96.0,40.6
Data Science,27,71.324000,97.0,43.5
Commerce,8,67.825000,83.7,54.6
data science,1,66.900000,66.9,66.9
Data Science,1,55.100000,55.1,55.1
Computer science,1,46.700000,46.7,46.7

In [63]:
# Q15: NumPy and Pandas Integration
import numpy as np
import pandas as pd





# 1. Convert the Final_Score column into a NumPy array
final_scores = df['Final_Score'].to_numpy()

# 2. Calculate statistics
mean_score = np.nanmean(final_scores)
median_score = np.nanmedian(final_scores)
std_deviation = np.nanstd(final_scores)
percentile_25 = np.nanpercentile(final_scores, 25)
percentile_75 = np.nanpercentile(final_scores, 75)


# Print the statistics
print("*** NumPy Statistical Summary of Final Scores ***")
print(f"Mean: {mean_score:.2f}")
print(f"Median: {median_score:.2f}")
print(f"Standard Deviation: {std_deviation:.2f}")
print(f"25th Percentile: {percentile_25:.2f}")
print(f"75th Percentile: {percentile_75:.2f}")
print("-------------------------------------------------")

# 3.  students whose Final_Score is above the overall mean
students_above_mean = df[df['Final_Score'] > mean_score]

print(f"\nNumber of students with Final Score above mean ({mean_score:.2f}): {len(students_above_mean)}")
display(students_above_mean[['Student_ID', 'Name', 'Department', 'Final_Score']])

*** NumPy Statistical Summary of Final Scores ***
Mean: 70.70
Median: 70.95
Standard Deviation: 13.96
25th Percentile: 60.45
75th Percentile: 82.28
-------------------------------------------------

Number of students with Final Score above mean (70.70): 42

   Student_ID            Name        Department  Final_Score
0     STU1001     Rahul Varma  Computer Science         82.7
4     STU1005       Asha Nair      Data Science         81.9
6     STU1007     Akhil Varma       Electronics         77.0
7     STU1008     Akhil Varma  Computer Science         79.2
8     STU1009      Diya Menon      Data Science         83.0
9     STU1010    Gokul Pillai  Computer Science         73.8
10    STU1011        Diya Das      Data Science         91.9
11    STU1012      Arun Reddy       Electronics         86.9
16    STU1017    Rahul Thomas      Data Science         91.1
17    STU1018      Priya Nair      Data Science         75.1
20    STU1021      Arun Varma          Commerce         73.2
23    STU1024  Fathima Joseph          Commerce         83.7
24    STU1025     Kiran Varma       Electronics         77.3
27    STU1028     Nikhil Nair      Data Science         77.1
30    STU1031      Amal Varma  Computer Science         85.5
33    STU1034        Amal Das  Computer Science         84.3
35    STU1036      Maya Menon       Electronics         84.2
37    STU1038    Kiran Pillai       Electronics         82.4
39    STU1040    Rohan Sharma  Computer Science         78.5
40    STU1041     Amal Pillai  Computer Science         94.5
41    STU1042     Arun Joseph  Computer Science         77.9
43    STU1044       Rahul Das  Computer Science         77.3
46    STU1047       Gokul Das      Data Science         74.8
47    STU1048     Priya Kumar      Data Science         77.3
48    STU1049     Asha Sharma      Data Science         97.0
51    STU1052      Gokul Nair          Commerce         79.3
52    STU1053      Maya Varma  Computer Science         71.0
55    STU1056     Vivek Varma      Data Science         93.3
56    STU1057    Rohan Pillai          Commerce         75.2
57    STU1058     Diya Thomas  Computer Science         92.3
58    STU1059       Anu Menon       Electronics         84.9
59    STU1060      Asha Menon      Data Science         87.9
60    STU1061  Fathima Sharma  Computer Science         70.8
61    STU1062    Kiran Pillai  Computer Science         96.0
64    STU1065    Rohan Sharma  Computer Science         83.5
66    STU1067    Rahul Thomas      Data Science         70.7
67    STU1068        Maya Das  Computer Science         83.7
72    STU1073   Swathi Joseph      Data Science         73.5
73    STU1074       Anu Kumar  Computer Science         83.4
74    STU1075      Gokul Nair      Data Science         70.9
77    STU1078  Fathima Sharma  Computer Science         75.2
79    STU1080      Diya Varma       Electronics         78.6

In [64]:
import pandas as pd
file_path= "/content/drive/MyDrive/DSA/Assessment/Assessment 2  Numpy & Pandas/student_performance.csv"
df_std_per=pd.read_csv(file_path)
df_std_per

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7
1,STU1002,Kiran Pillai,Male,Computer Science,24.0,75.5,70.3,63.1,65.1,62.3,60.3
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1
3,STU1004,Rahul Sharma,Female,Data Science,25.0,80.4,65.8,50.7,52.6,48.8,57.2
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9
...,...,...,...,...,...,...,...,...,...,...,...
75,STU1076,Priya Kumar,Female,Computer Science,24.0,99.3,46.9,57.6,29.5,57.1,47.2
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2
78,STU1079,Meera Thomas,Male,Electronics,23.0,99.4,64.6,66.5,61.8,52.5,63.4
79,STU1080,Diya Varma,Male,Electronics,19.0,86.4,80.5,94.3,58.6,74.9,78.6

In [72]:
#16. A. Data Cleaning
#16.1 Identify missing values.

# Identify missing values in each column
count = df.isnull().sum()
print(" Missing Values Count per Column ")
print(count[count > 0])

 Missing Values Count per Column
Age             3
Attendance      3
Python_Score    2
Pandas_Score    2
NumPy_Score     2
Final_Score     2
dtype: int64

In [68]:
#16.2. Handle missing numerical values appropriately (replacing with means)
numerical_cols = df_std_per.select_dtypes(include=['float64', 'int64']).columns

for col in numerical_cols:
    if df_std_per[col].isnull().any():
        col_mean = df_std_per[col].mean()
        df_std_per[col] = df_std_per[col].fillna(col_mean)
        print(f"Filled missing values in '{col}' with its mean: {col_mean:.2f}")

# Verify if any missing values remain
remaining_missing = df_std_per.isnull().sum().sum()
print(f"\nTotal remaining missing values: {remaining_missing}")

Filled missing values in 'Age' with its mean: 22.01
Filled missing values in 'Attendance' with its mean: 81.67
Filled missing values in 'Python_Score' with its mean: 72.82
Filled missing values in 'Pandas_Score' with its mean: 70.37
Filled missing values in 'NumPy_Score' with its mean: 68.57
Filled missing values in 'Final_Score' with its mean: 70.70

Total remaining missing values: 0

In [74]:
# 16.B. Feature Engineering on df_std_per

# 1. Create 'Average_Score' using the Python, SQL, Pandas, and NumPy scores
subject_cols = ['Python_Score', 'SQL_Score', 'Pandas_Score', 'NumPy_Score']
df_std_per['Average_Score'] = df_std_per[subject_cols].mean(axis=1)

# 2. Create 'Pass_Status' column
df_std_per['Pass_Status'] = df_std_per['Average_Score'].apply(lambda score: 'Pass' if score >= 50 else 'Fail')

# Display the updated DataFrame to verify
display(df_std_per[['Name', 'Python_Score', 'SQL_Score', 'Pandas_Score', 'NumPy_Score', 'Average_Score', 'Pass_Status']].head())

,Name,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Average_Score,Pass_Status
0,Rahul Varma,89.4,86.3,81.9,76.7,83.575,Pass
1,Kiran Pillai,70.3,63.1,65.1,62.3,65.200,Pass
2,Fathima Joseph,79.9,80.4,65.3,68.0,73.400,Pass
3,Rahul Sharma,65.8,50.7,52.6,48.8,54.475,Pass
4,Asha Nair,90.1,82.9,72.4,87.7,83.275,Pass

In [75]:
# 1. Top 5 students based on Average_Score
top_5_students = df_std_per.sort_values(by='Average_Score', ascending=False).head(5)
print("--- Top 5 Students Based on Average_Score ---")
display(top_5_students[['Name', 'Department', 'Average_Score']])

--- Top 5 Students Based on Average_Score ---

            Name        Department  Average_Score
10      Diya Das      Data Science         95.625
61  Kiran Pillai  Computer Science         95.200
8     Diya Menon      Data Science         92.125
16  Rahul Thomas      Data Science         89.350
35    Maya Menon       Electronics         87.800

In [76]:
# 2. Department having the highest average score
dept_avg_scores = df_std_per.groupby('Department')['Average_Score'].mean()
highest_dept = dept_avg_scores.idxmax()
highest_score = dept_avg_scores.max()

print(f"Department with the highest average score: {highest_dept} ({highest_score:.2f})")

Department with the highest average score: Electronics (74.06)

In [77]:
# 3. Average attendance by department
avg_attendance_dept = df_std_per.groupby('Department')['Attendance'].mean().reset_index()
print("--- Average Attendance by Department ---")
display(avg_attendance_dept)

--- Average Attendance by Department ---

         Department  Attendance
0     Data Science    76.700000
1          Commerce   77.437500
2  Computer Science   82.768025
3  Computer science   92.100000
4      Data Science   82.076768
5       Electronics   80.576923
6      data science   81.672727

In [78]:
# 4. Number of students who passed and failed
pass_fail_counts = df_std_per['Pass_Status'].value_counts().reset_index()
pass_fail_counts.columns = ['Pass_Status', 'Number_of_Students']
print("--- Number of Students Who Passed and Failed ---")
display(pass_fail_counts)

--- Number of Students Who Passed and Failed ---

  Pass_Status  Number_of_Students
0        Pass                  72
1        Fail                   8

In [87]:
#D
import pandas as pd
import numpy as np

# 1. Restore df_std_per with student performance data
file_path = "/content/drive/MyDrive/DSA/Assessment/Assessment 2  Numpy & Pandas/student_performance.csv"
df_std_per = pd.read_csv(file_path)

# Clean missing values
numerical_cols = df_std_per.select_dtypes(include=['float64', 'int64']).columns
for col in numerical_cols:
    df_std_per[col] = df_std_per[col].fillna(df_std_per[col].mean())

# Re-engineer required features
subject_cols = ['Python_Score', 'SQL_Score', 'Pandas_Score', 'NumPy_Score']
df_std_per['Average_Score'] = df_std_per[subject_cols].mean(axis=1)
df_std_per['Pass_Status'] = df_std_per['Average_Score'].apply(lambda score: 'Pass' if score >= 50 else 'Fail')

# Standardize department names
df_std_per['Department'] = df_std_per['Department'].str.strip().str.title()

# 2. Generate the department summary
df_dept_summary = df_std_per.groupby('Department').agg(
    Total_Students=('Student_ID', 'count'),
    Average_Score=('Average_Score', 'mean'),
    Average_Attendance=('Attendance', 'mean'),
    Pass_Count=('Pass_Status', lambda x: (x == 'Pass').sum()),
    Fail_Count=('Pass_Status', lambda x: (x == 'Fail').sum())
).reset_index()

# Round numerical metrics
df_dept_summary['Average_Score'] = df_dept_summary['Average_Score'].round(2)
df_dept_summary['Average_Attendance'] = df_dept_summary['Average_Attendance'].round(2)

# Display the final summary DataFrame
display(df_dept_summary)

,Department,Total_Students,Average_Score,Average_Attendance,Pass_Count,Fail_Count
0,Commerce,8,68.81,77.44,8,0
1,Computer Science,30,69.96,83.08,25,5
2,Data Science,29,70.07,81.88,26,3
3,Electronics,13,74.06,80.58,13,0

In [80]:
#17


import pandas as pd
file_path= "/content/drive/MyDrive/DSA/Assessment/Assessment 2  Numpy & Pandas/sales.csv"
df_sale=pd.read_csv(file_path)
df_sale

,Order_ID,Order_Date,Product,Category,Region,Sales,Quantity,Discount,Profit
0,ORD5001,2026-06-10,Office Chair,Furniture,East,142.1,1.0,0.02,12.78
1,ORD5002,2026-04-25,USB Hub,Accessories,North,51.52,2.0,0.08,4.57
2,ORD5003,2026-03-07,Monitor,Computers,West,648.0,4.0,0.1,86.32
3,ORD5004,2026-03-19,Office Chair,Furniture,North,290.0,2.0,0.0,47.77
4,ORD5005,2026-01-25,Tablet,Computers,North,304.0,1.0,0.05,23.43
...,...,...,...,...,...,...,...,...,...
175,ORD5176,2026-05-02,External SSD,Storage,North,418.0,4.0,0.05,80.35
176,ORD5177,2026-01-30,Headphones,Accessories,North,308.75,5.0,0.05,86.16
177,ORD5178,2026-03-20,USB Hub,Accessories,South,166.6,7.0,0.15,28.42
178,ORD5179,2026-05-27,USB Hub,Accessories,South,89.6,4.0,0.2,15.18
179,ORD5180,2026-02-11,Wireless Mouse,Accessories,West,56.1,3.0,0.15,16.83

In [85]:
df_sale['Order_Date'] = pd.to_datetime(df_sale['Order_Date'], format='mixed', dayfirst=True)
print("Order_Date converted to:", df_sale['Order_Date'].dtype)

Order_Date converted to: datetime64[ns]

In [84]:
missing_sales = df_sale.isnull().sum()
print("Missing Values Count per Column in df_sale:")
print(missing_sales[missing_sales > 0])

Missing Values Count per Column in df_sale:
Region      1
Quantity    1
Profit      1
dtype: int64

In [ ]:
import pandas as pd

# 1. Calculate general metrics
total_sales = df_sale['Sales'].sum()
total_profit = df_sale['Profit'].sum()
avg_sales = df_sale['Sales'].mean()

print(f"Total Sales: ${total_sales:,.2f}")
print(f"Total Profit: ${total_profit:,.2f}")
print(f"Average Sales: ${avg_sales:,.2f}\n")

# 2. Top 5 products based on sales
top_products = df_sale.groupby('Product')['Sales'].sum().reset_index()
top_products_sorted = top_products.sort_values(by='Sales', ascending=False).head(5)
print("--- Top 5 Products by Sales ---")
display(top_products_sorted)
print()

# 3. Region generating the highest sales
region_sales = df_sale.groupby('Region')['Sales'].sum().reset_index()
best_region = region_sales.sort_values(by='Sales', ascending=False).iloc[0]
print(f"Region with Highest Sales: {best_region['Region']} (${best_region['Sales']:,.2f})")

In [89]:
import pandas as pd
import numpy as np

# Convert columns to numeric types to fix aggregation errors
df_sale['Sales'] = pd.to_numeric(df_sale['Sales'], errors='coerce')
df_sale['Profit'] = pd.to_numeric(df_sale['Profit'], errors='coerce')
df_sale['Discount'] = pd.to_numeric(df_sale['Discount'], errors='coerce')

# --- Part C: Category Analysis ---
category_summary = df_sale.groupby('Category').agg(
    Total_Sales=('Sales', 'sum'),
    Total_Profit=('Profit', 'sum'),
    Average_Discount=('Discount', 'mean')
).reset_index()

# Sort by Total Sales in descending order
category_summary = category_summary.sort_values(by='Total_Sales', ascending=False)

print("--- Category Analysis Summary ---")
display(category_summary)

# --- Part D: Extract Data for Business Insights ---
# 1. Most profitable category
most_profitable_cat = category_summary.sort_values(by='Total_Profit', ascending=False).iloc[0]

# 2. Region with highest sales
region_sales = df_sale.groupby('Region')['Sales'].sum().reset_index()
best_region = region_sales.sort_values(by='Sales', ascending=False).iloc[0]

# 3. Product with highest sales
product_sales = df_sale.groupby('Product')['Sales'].sum().reset_index()
best_product = product_sales.sort_values(by='Sales', ascending=False).iloc[0]

print("\n--- Key Business Findings ---")
print(f"1. Most Profitable Category: {most_profitable_cat['Category']} (${most_profitable_cat['Total_Profit']:,.2f})")
print(f"2. Region with Highest Sales: {best_region['Region']} (${best_region['Sales']:,.2f})")
print(f"3. Product with Highest Sales: {best_product['Product']} (${best_product['Sales']:,.2f})")

--- Category Analysis Summary ---

           Category  Total_Sales  Total_Profit  Average_Discount
2         Computers     53696.60       8971.75          0.063514
4  Office Equipment     13719.30       2176.64          0.058421
1       Accessories     12958.28       2061.66          0.078780
3         Furniture      7329.46       1113.32          0.074815
5           Storage      5316.30        806.16          0.075385
0      accessories        130.00         30.94          0.000000

--- Key Business Findings ---
1. Most Profitable Category: Computers ($8,971.75)
2. Region with Highest Sales: West ($37,314.18)
3. Product with Highest Sales: Laptop ($33,995.00)